services:
  rag_api:
    build: .
    container_name: rag_api
    env_file:
      - .env
    volumes:
      - ./data:/app/data
      - ./state:/app/state
      - ./faiss_data:/app/faiss_data
    ports:
      - "8000:8000"
    restart: unless-stopped